{{- range $name, $svc := .Values.microservices }}
{{- if $svc.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $svc.name }}-secret
  labels:
    {{- include "microservice.labels" $svc | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := $svc.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
